### ISSUE TITLE
C language

### ISSUE THREAD

**Issue by MyTDT-Mysoft** [smarx/othw#4]
would be nice to have one example for C, using for example libcurl, and some base64 library
as all examples posted there either have cryptic stuff like regex, or  uses classes and other OOP stuff, so a clean C version would be very useful.

**Comment by greg-db** [comment]
Thanks! I'll send this along to the team as a request for a C example like that.

**Comment by rogebrd** [comment]
Hello, we implement OAuth following the standard protocol so you can use any generic oauth library. A quick search online I found this library: https://github.com/sinemetu1/twitc.

Otherwise, since we don't have an official C SDK, we do recommend you use a language we support officially! Hope this helps!
